import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConsoleFooter } from "@/components/footer/Footer";
import { Header } from "@/components/home/header/Header";
import StoreProvider from "./StoreProvider";
import toast, { Toaster } from "react-hot-toast";

// Load the Poppins font with correct configuration
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins", // CSS variable for global use
  display: "swap", // Ensures better loading performance
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`antialiased ${poppins.className}`} >
        <Toaster position="top-center" />
        <StoreProvider>
          <AntdRegistry>
            <Header />
            {children}
            <ConsoleFooter />
          </AntdRegistry>
        </StoreProvider>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Poppins } from "next/font/google";
// import "./globals.css";
// import { AntdRegistry } from "@ant-design/nextjs-registry";
// import { ConsoleFooter } from "@/components/footer/Footer";
// import { Header } from "@/components/home/header/Header";
// import StoreProvider from "./StoreProvider";
// import toast, { Toaster } from "react-hot-toast";

// const poppins = Poppins({
//   variable: "--font-poppins",
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={`${poppins.variable} antialiased`}>
//         <Toaster position="top-center" />
//         <StoreProvider>
//           <AntdRegistry>
//             <Header />
//             {children}
//             <ConsoleFooter />
//           </AntdRegistry>
//         </StoreProvider>
//       </body>
//     </html>
//   );
// }
